inherit_gem:
  bixby: bixby_default.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '**/*.gemspec' # these would normally be inherited from bixby
    - 'config/**/*'

Naming/FileName:
  Exclude:
    - "**/Capfile"
    - "**/Gemfile"
    - "**/*.rake"

Metrics/BlockLength:
  Exclude:
    - "spec/importers/iris_mapper_spec.rb"
    - "spec/importers/importer_spec.rb"
    - "app/controllers/catalog_controller.rb"
    
Style/IfUnlessModifier:
  Exclude:
    - "app/models/ability.rb"
