inherit_gem:
  bixby: bixby_default.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '**/*.gemspec' # these would normally be inherited from bixby
    - 'config/**/*'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'spec/importers/importer_spec.rb'

Naming/FileName:
  Exclude:
    - "**/Capfile"
    - "**/Gemfile"
    - "**/*.rake"

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/importers/iso_zip_mapper.rb'

Metrics/LineLength:
  Exclude:
    - "app/importers/iris_mapper.rb"
    - 'app/importers/iso_zip_mapper.rb'

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - "spec/lib/tasks/import_rake_spec.rb"  
