inherit_gem:
  bixby: bixby_default.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '**/*.gemspec' # these would normally be inherited from bixby
    - 'config/**/*'

Naming/FileName:
  Exclude:
    - "**/Capfile"
    - "**/Gemfile"
    - "**/*.rake"

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - "app/importers/iris_mapper.rb"

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false
