development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['DEV_FEDORA_URL'] || 'http://127.0.0.1:8984/rest' %>
  base_path: <%= ENV['DEV_FEDORA_BASE'] || "/dev" %>

test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['TEST_FEDORA_URL'] || 'http://127.0.0.1:8986/rest' %>
  base_path: /test

production:
  user: fedoraAdmin
  password: <%= ENV['FEDORA_PASSWORD'] %>
  url: <%= ENV['FEDORA_URL'] %>
  base_path: /prod
